#!/usr/bin/env ruby
# coding: utf-8

require 'strscan'
require './cons'
require './generator'

# for debug
# require 'ruby-debug-ide'
# require 'debase'

def tokenize str
  scanner = StringScanner.new(str)
  tokenized = []

  until scanner.eos?
    scanner.scan(/\s+/) ? nil : 
    scanner.scan(/\(/) ? tokenized << scanner.matched :
    scanner.scan(/\)/) ? tokenized << scanner.matched :
    scanner.scan(/[a-z0-9A-Z\;\:\"\'\-\=\_\*\?\!\>\<\/]+/) ? tokenized << scanner.matched :
    nil                                                    
  end
  tokenized  
end

# todo implement
def atom token
  return token
end

def read_from tokens
  token = tokens[0]
  tokens.delete_at(0)

  if token == "("
    cell = ConsCell.new
    while tokens[0] != ")"
      cell.push read_from tokens
    end
    
    tokens.delete_at(0)
    return cell
  end
  return atom token
end

def replace_scm_chars tokens
  r = Array.new
  # replace chars that cannot use in C++ source
  tokens.each { |token|
    token.gsub!("?", "_")
    token.gsub!("!", "__")
    token.gsub!("-", "_")
    r << token
  }
  r
end


if ARGV.size == 0
  puts "usage: out2cpp inputfile"
  exit
end

inputFileName = ARGV[0]
outputFileName = File.basename(inputFileName, ".out") + ".cpp"

input = File.open(inputFileName)
vmSource = input.read

puts "creating tokens..."
tokens = tokenize(vmSource)
tokens = replace_scm_chars(tokens)
parsed = read_from tokens


result_registers_list = car(parsed)
modified_registers_list = cadr(parsed)
codes_list = car cddr(parsed)
puts "generating codes.."

def linear_list_to_array list
  r = Array.new
  if car(list)
    r << car(list)
  end

  if cdr(list)
    r << linear_list_to_array(cdr(list))
  end

  r.flatten
end

result_registers = linear_list_to_array(result_registers_list) # maybe unnessessary
modified_registers = linear_list_to_array(modified_registers_list) # maybe unnessessary
codes = linear_list_to_array(codes_list)

# code with labels 
labeled_codes = Array.new
labeled_codes << Array.new
labeled_codes[0] << "init" # for initial non-labeled codes

codes.each {|code|
  if code.is_a?(String)
    labeled_codes << Array.new 
    labeled_codes[-1] << code
  else
    labeled_codes[-1] << code
  end
}

prototypes = generate_prototypes labeled_codes
functions = generate_functions labeled_codes

out = open(outputFileName, "w")

prototypes.each { |prototype|
  out.puts prototype
}

functions.each { |function|
  p function
  out.puts function
}

out.close
