#pragma once
void compiled_procedure_start();
void entry1();
void compiled_branch7();
void primitive_branch6();
void after_call8();
void true_branch3();
void false_branch4();
void compiled_branch10();
void primitive_branch9();
void after_call11();
void compiled_branch13();
void primitive_branch12();
void after_call14();
void compiled_branch_16();
void primitive_branch15();
void after_call17();
void after_if5();
void after_lambda2();
